
name: build-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.SAMPLE_DIST_CERT_P12 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.SAMPLE_PROV_PROF_BASE64 }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$SAMPLE_DIST_CERT_P12" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$SAMPLE_PROV_PROF_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p qburst build.keychain security default-keychain -s build.keychain
          security unlock-keychain -p qburst build.keychain

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Build app
        run: fastlane custom_lane
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}


